BMP_HEADER_BSIZE = 14
BMP_INFO_HEADER_BSIZE = 40

BASE_PATH = 'assets/'
RESULT_PATH = 'result/'

CAT256_BMP_PATH = BASE_PATH + 'cat_256.bmp'
CAT256_PCX_PATH = BASE_PATH + 'cat_256.pcx'
CAT16_BMP_PATH = BASE_PATH + 'cat_16.bmp'
FISH_PATH = BASE_PATH + 'fish.bmp'
TIGER_PATH = BASE_PATH + 'tiger.pcx'

WATERMARK_PATH = BASE_PATH + 'watermark.bmp'

SECRET_TEXT_PATH = BASE_PATH + 'text.txt'


MONOCHROME_PATH = RESULT_PATH + 'mono.bmp'
BORDER_PATH = RESULT_PATH + 'border.bmp'
ROTATE_PATH = RESULT_PATH + 'rotate.bmp'
SECRET_IMG_PATH = RESULT_PATH + 'encode.bmp'
DECODED_TEXT_PATH = RESULT_PATH + 'text.txt'
CONVERTED_PATH = RESULT_PATH + 'convert.bmp'
CONVERTED_PATH1 = 'convert.bmp'